name: Cache Workflow

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create dummy deps directory
        run: |
          mkdir -p ~/.cache/mydeps
          echo "hello" > ~/.cache/mydeps/file.txt

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/mydeps
          key: cache-1d18359

      - name: prime-cache-1d18359
        run: "Cache result: ${{ steps.cache.outputs.cache-hit }}"
