name: Cache Example

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/mydeps
          key: cache-1d18359

      - name: prime-cache-1d18359
        run: echo "Cache result: ${{ steps.cache-step.outputs.cache-hit }}"
