name: Dependency Caching Challenge

on: [push] # Run this every time I push code

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-step # We give it an ID so we can check it later
        uses: actions/cache@v4
        with:
          path: ~/dummy-dependencies # The folder we want to "remember"
          key: cache-1d18359 # The specific ID required by your assignment

      - name: prime-cache-1d18359
        run: echo "Cache hit? ${{ steps.cache-step.outputs.cache-hit }}"
